### PR TITLE
Initial dropdown menu

### PR DESCRIPTION
**Pull request by jpatch22**
### Summary
Create initial dropdown menu

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [ ] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [ ] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

### CODE REVIEW

**Review by Evanyl — APPROVED** [review]
LGTM!

**Review by forbesashli — CHANGES_REQUESTED** [review]
SignalUtil calls a capital 'D' definitions.py when it should be either both upper or lower case

**Comment by Evanyl** [comment]
Addressed the rename @forbesashli

**Review by forbesashli — APPROVED** [review]
Looks good to me, drop down works

**Pull request merged**
