### PR TITLE
Log4J Rework

### PR DESCRIPTION
**Pull request by Lucien950**
### Summary
- Log4J.properties files now properly generates on windows
- This file now generates in a separate file, and only once at generate step (rather than every time at build step)
    - this is because this is a shared file that is used throughout the process
> NOTE: I don't know how to point to a custom log4j.properties file for stm, but if there is a way i would prefer to generate it in the working directory rather than in the user home folder.

### Changelist 

- CMakeLists.txt
- generate_cube_code.py
- generate_log4j_properties.py

### Testing Done

- CI

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [x] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [x] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

### CODE REVIEW

**Comment by Lucien950** [comment]
TODO consider not autogenerating Log4J configs, and make sure this is supported on the new boards (perhaps pr into latest STM branch)

**Comment by gtaharaedmonds** [comment]
can we close this? is Ninja support something we still care about

**Comment by Lucien950** [comment]
> can we close this? is Ninja support something we still care about

I don't think i'm necessarily caught up on the ninja support, I just want to make sure that log4j is standardized on all operating systems, and that if there are changes we decide on in the future they can be synced up globally.

**Comment by Lucien950** [comment]
Also ninja breaks with this now
```
CMake Error:
  Running

   'C:/Users/[user]/AppData/Local/Programs/CLion Nova/bin/ninja/win/x64/ninja.exe' '-C' 'C:/Users/[user]/Documents/School/fsae/Consolidated-Firmware/build_fw_deploy' '-t' 'recompact'

  failed with:

   ninja: warning: phony target 'firmware/thruna/BMS/BMS_app.hex' names itself as an input; ignoring [-w phonycycle=warn]

  ninja: warning: phony target 'firmware/thruna/BMS/BMS_app.asm' names itself
  as an input; ignoring [-w phonycycle=warn]

  ninja: warning: phony target 'firmware/thruna/BMS/BMS_app_metadata.hex'
  names itself as an input; ignoring [-w phonycycle=warn]

  ninja: warning: phony target 'firmware/thruna/BMS/BMS.hex' names itself as
  an input; ignoring [-w phonycycle=warn]

  ninja: error: build.ninja:2089: multiple rules generate
  firmware/thruna/BMS/BMS_app.hex [-w dupbuild=err]
```

**Comment by Lucien950** [comment]
Fixed in 192ff4093ebcaf85b39aab25223c767e322472e8

**Pull request closed without merging**
