### PR TITLE
File structure for Inverter GUI software and EEPROM config files.

### PR DESCRIPTION
**Pull request by Eddy13013**
…eeprom configurations.

### Summary
New PR for inverter software folder. Under the boards folder you can find the new INVERTER folder. We can use this to store the inverter GUI software. Nested inside there is a folder to store eeprom config profiles for each inverter. I suggest we use the dated naming structure I started with and save file iterations as we make changes. This way we can easily and quickly load an old set of configs during testing.

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [ ] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [ ] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

### CODE REVIEW

**Comment by pasitlaothamatas** [comment]
@Eddy13013 can you rebase onto upstream master

**Comment by pasitlaothamatas** [comment]
I was told that Iq and Id limits were changed in the configuration files. Are these changes needed? If these changes are not needed to get the motors spinning, have they been reverted?

**Comment by pasitlaothamatas** [comment]
Should we give the file names sth more descriptive instead of dates? Any changes made to the config profiles should be tracked by git so i dont think having a date there is necessary

**Comment by pasitlaothamatas** [comment]
whats the difference between the files in `conf/` and `saved_eeprom_configs/` ?

**Comment by timbitss** [comment]
> whats the difference between the files in `conf/` and `saved_eeprom_configs/` ?

image

@Eddy13013 I think we can take out the save_eeprom_configs folder and simply let the RMS GUI generate new files in the conf folder as we program the inverters. This way, we avoid having to rename the files each time. The GUI generates the date of programming which is nice too.

We could also add a small README.txt stating that the left inverter is serial no. 1846 and the right inverter is serial no. 1847 for easy identification

**Comment by timbitss** [comment]
> I was told that Iq and Id limits were changed in the configuration files. Are these changes needed? If these changes are not needed to get the motors spinning, have they been reverted?

The changes were made so that both motors have the same parameters. I don't see a reason to revert unless an issue arises. We can do a review of the eeprom settings sometime soon.

**Comment by pasitlaothamatas** [comment]
@timbitss @Eddy13013 any updates on how we will proceed with this?

**Comment by timbitss** [comment]
inactive

**Comment by timbitss** [comment]
reoopened lol

**Comment by pasitlaothamatas** [comment]
> @timbitss @Eddy13013 any updates on how we will proceed with this?

^???

**Comment by timbitss** [comment]
refer to PR #756 since I don't have push permissions onto edwin's branch

**Pull request closed without merging**
