### PR TITLE
Update Clang Format to 17.0.1 (and support CLion)

### PR DESCRIPTION
**Pull request by Lucien950**
### Resolved Issues

Fixes [SW-66](https://ubcformulaelectric.atlassian.net/browse/SW-66)

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [x] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [x] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

[SW-66]: https://ubcformulaelectric.atlassian.net/browse/SW-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Lucien950** [comment]
Fixes [SW-66](https://ubcformulaelectric.atlassian.net/browse/SW-66)

**Review by gtaharaedmonds — COMMENTED** [review]
lgtm

**Review by gtaharaedmonds — CHANGES_REQUESTED** [review]
lgtm

**Review by gtaharaedmonds — APPROVED** [review]
LGTM

**Pull request merged**
