### PR TITLE
Split up stateless and all-states specifications

### PR DESCRIPTION
**Pull request by thekenu**
### Summary

In `specs.md`, most of what's considered "stateless" are supposed to run in every state. A better name would be "all states". Furthermore,  some other considered "stateless" _really_ is stateless. That is, they should run outside of the state machine (e.g. the boot startup message).

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [ ] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [ ] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

### CODE REVIEW

**Comment by thekenu** [comment]
All states means something that should be done in every state. Whereas stateless would be something done outside of the state machine. For example, sending the startup CAN message happens before the state machine starts.

**Comment by garethellis0** [comment]
Right, but could we just everything that's not in a particular state be "stateless"? Just seems like it will be a little tricky to sort specs in the future, and ideally we keep this a simple as possible so that people actually use/update it.

**Comment by thekenu** [comment]
Do you mean that things that run in every state should also be stateless?

My issue with `Stateless` right now is that it represents two types of specs:
- Those that should run in every state
- Those that should run once outside of the state machine

And it just seems misleading to group them together

**Comment by garethellis0** [comment]
I just can't think of many things that are in the first group but not the second group. They're really just specs that should be enforced at all times, instead of in a specific state.

**Comment by thekenu** [comment]
I guess that's a valid way to interpret what Stateless means as well. I was hoping that every `AllStates` specs would directly go in the `RunAllStatesTick` functions we have been adding, while `Stateless` specs wouldn't. 

In any case, I'm not super attached to having this change merged in, so it you think having `Stateless` and `AllStates` would make the specs harder to maintain I'll be happy to close this PR too! :taco:

**Comment by garethellis0** [comment]
Yeah, I really don't think they're worth it, really want to keep the specs as easy to maintain as possible, even at the cost of some organisation.

**Pull request closed without merging**
