### PR TITLE
Remove Vscode Prelaunch Tasks for Tests

### PR DESCRIPTION
**Pull request by liam-ilan**
### Changelist 
- Removed prelaunch tasks from tests. This was causing an error to be thrown since we no longer use Vscode tasks.

### Testing Done
- Ran tests with no warnings in Vscode.

### Resolved Tickets
- https://ubcformulaelectric.atlassian.net/browse/FIRM-94
- [FIRM-99](https://ubcformulaelectric.atlassian.net/browse/FIRM-99)

[FIRM-99]: https://ubcformulaelectric.atlassian.net/browse/FIRM-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Lucien950** [comment]
can you investigate if there's a way to launch cmake build tasks from launch.json? cause there's a few ways I see this system working

- control shift b tasks which trigger cmake builds
- control shift b tasks as per usual as last year, but manual preset encoding
- leaving the responsibility to the user to build before running
- cmake launch configurations?? surely has to be a thing
- other tech I do not know about

**Review by Lucien950 — CHANGES_REQUESTED** [review]
can you investigate if there's a way to launch cmake build tasks from launch.json? cause there's a few ways I see this system working

- control shift b tasks which trigger cmake builds
- control shift b tasks as per usual as last year, but manual preset encoding
- leaving the responsibility to the user to build before running
- cmake launch configurations?? surely has to be a thing
- other tech I do not know about

I just don't know too much about this atm

**Comment by liam-ilan** [comment]
Will do! - found this https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md

**Comment by Lucien950** [comment]
hot I will make changes based on that in [FIRM-99](https://ubcformulaelectric.atlassian.net/browse/FIRM-99)

**Review by philam2001 — COMMENTED** [review]
Wait does load cmake only load it for the build test fw?

**Review by Lucien950 — APPROVED** [review]

**Pull request merged**
